GET http://localhost:5000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjUsIm5hbWUiOiJrdXJvQGdtYWlsLmNvbSIsImlhdCI6MTY5MzEzNTc4MSwiZXhwIjoxNjkzMTM1ODAxfQ.WGBusxYWbCTYuYqlsydpJ2jKODOjJerK1P-OkY57qvs

###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name": "ksaduro",
    "password": "123",
}